<a href="https://colab.research.google.com/github/rutul7802/ML---Practicals/blob/main/ML_Prac_1(iv)Numpy_Arrays)18BECE30553.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. NUMPY ARRAY**

In [ ]:
#create numpy ndarray object
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
#Using tuple to create Numpy array
import numpy as np
arr = ((1,2,3,4,5,6))
print(arr)

(1, 2, 3, 4, 5, 6)


## **1.1 Array having no. of different dimensions,Accessing different Elements & Slicing**

---



In [ ]:
#0-D Arrays
print("******0-D Array*******")
import numpy as np
array = np.array(78)
print(array)
print('\n')

#1-D Arrays
print("******1-D Array*******")
import numpy as np
arr = np.array([20,30,40,56])
print(arr)
#[Accessing 3rd element]
print("Accessing 3rd element:",arr[2])

#[Slicing elements(include starting index but exclude end index)]
print("Slicing elements are:",arr[1:3])
print("Slice elements from 2 to end of array:",arr[2:])
print("Slice elements from the beginning to index 3 (which is not included):",arr[:3])
#Slicing using step value
print("Slice the array using step value:",arr[0:3:2])
print("Slice the array using step value:",arr[0:3:1])
print("Slice the array using step value:",arr[1:3:2])
print("Slice the array using step value:",arr[::2])

#[[Negative Slicing]]
print("Slice from the index 3 from the end to index 1 from the end:",arr[-3:-1])
print('\n')

#2-D Arrays
print("******2-D Array*******")
import numpy as np
arr = np.array([[30,45,67],[47,36,89]])
print(arr)
print("Accesing 3 element from 1st dim:",arr[0,2])
print("Accesing 3 element from 2nd dim:",arr[1,2])
#[Slicing in 2-D Array]
print("From the second element slice the element from index 0 but not index 2",arr[1,0:2])
print("From the Both the arrays choose element at index 1 is:",arr[0:2,1])
print("From Both the arrays choose element at position index 0 but not at 1 is:",arr[0:2,0:1])

print('\n')

#3-D Arrays
print("******3-D Array*******")
import numpy as np
arr = np.array([[[20,30,40],[28,39,79]],[[56,78,90],[45,56,23]]])
print(arr)
print("*****Checking dimensions********")
print(arr.ndim)
print("Accesing 3rd element of second array of first array:",arr[0,1,2])
print("Accesing 2nd element of first array of third array:",arr[1,0,1])
print("Accesing 1st element of second array of third array:",arr[1,1,0])
print('\n')

#Arrays having higher dimensions
print("******Higher dimensions array*******")
import numpy as np
# You can define any no of dimensions using 'ndmin' argument
arr = np.array([2,3,4,5,6], ndmin= 5)
print(arr)
print("No of dimensions of array is:",arr.ndim)
print('\n')

#Negative Indexing
print("**********Negative Indexing***********")
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]] )
print("Last element of 2nd dimension:",arr[1,-1])
print("Last element of 1st dimension:",arr[0,-3])


******0-D Array*******
78


******1-D Array*******
[20 30 40 56]
Accessing 3rd element: 40
Slicing elements are: [30 40]
Slice elements from 2 to end of array: [40 56]
Slice elements from the beginning to index 3 (which is not included): [20 30 40]
Slice the array using step value: [20 40]
Slice the array using step value: [20 30 40]
Slice the array using step value: [30]
Slice the array using step value: [20 40]
Slice from the index 3 from the end to index 1 from the end: [30 40]


******2-D Array*******
[[30 45 67]
 [47 36 89]]
Accesing 3 element from 1st dim: 67
Accesing 3 element from 2nd dim: 89
From the second element slice the element from index 0 but not index 2 [47 36]
From the Both the arrays choose element at index 1 is: [45 36]
From Both the arrays choose element at position index 0 but not at 1 is: [[30]
 [47]]


******3-D Array*******
[[[20 30 40]
  [28 39 79]]

 [[56 78 90]
  [45 56 23]]]
*****Checking dimensions********
3
Accesing 3rd element of second array of first ar

## **1.2 Data Conversion In Numpy Array**

In [ ]:
import numpy as np
arr = np.array([1.2,1.3,34.9])
newarr = arr.astype(int)
print("Converting Float to Integer:",newarr)
print(newarr.dtype)

#Int To Boolean
import numpy as np
arr = np.array([1,0,9])
newarr1 = arr.astype(bool)
print("Converting Int TO Boolean:",newarr1)

Converting Float to Integer: [ 1  1 34]
int64
Converting Int TO Boolean: [ True False  True]


## **1.3 Copy And View In Numpy Array**

In [ ]:
#Copy Of an Array
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
x= arr.copy()
arr[0]=78
print("Array after change:",arr)
print("Array after copied from array",x)

Array after change: [78  2  3  4  5  6  7]
Array after copied from array [1 2 3 4 5 6 7]


In [ ]:
#View Of an Array
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
x= arr.view()
arr[0]=78
print("View of Array after adding value:",arr)
print("View of an array",x)
print("\n")

#View After Change in value of  View
import numpy as np
arr= np.array([12,23,34,55,67,78,89])
x= arr.view()
x[0]=7820
print("View of Array after change value of view:",arr)
print("View of an array",x)
print("\n")

#To check whether Array Owns It's Data or not using BASE attribute[As Copies are the new array but Views are just view of original data]
import numpy as np
arr= np.array([1,2,3,4,5])
x= arr.copy()
y= arr.view()
print("As x returns :",x.base) #It returns none because that array owns data
print("As y returns",y.base) #It returns Original array because it doesn't owns data


View of Array after adding value: [78  2  3  4  5  6  7]
View of an array [78  2  3  4  5  6  7]


View of Array after change value of view: [7820   23   34   55   67   78   89]
View of an array [7820   23   34   55   67   78   89]


As x returns : None
As y returns [1 2 3 4 5]


## **1.4 Shape and Reshape of an Array**

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Shape of an array is:",arr.shape)
print("\n")
import numpy as np
arr= np.array([1,2,3,4], ndmin=5)
print("Value of an array is:",arr)
print("Shape of another Array:",arr.shape)


Shape of an array is: (2, 4)


Value of an array is: [[[[[1 2 3 4]]]]]
Shape of another Array: (1, 1, 1, 1, 4)


In [ ]:
#Reshape of an array
#[1-D to 2-D]
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = arr.reshape(3,2)
print("Changing shape of array from 1-D to 2-D:","\n",newarr)
print("\n")

#[1-D to 3-D]
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print("Changing shape of 1-D array to 3-D array:","\n",newarr)
print("\n")

#[To check whether returned array is Copy or View]
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Changing the array shape:","\n",arr.reshape(2,3))
print("The Returned array is:",arr.reshape(2,3).base,"so it is View")#Because it returned original array
print("\n")

#[Unknown Dimensions]-Only one dimension is to be allowed to unknown
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,-1,2)
print("Array changing shape froom 1-D to 3-D:","\n",newarr)
print("\n")

#[Flattening the array]-Change Multidimentional Array to 1-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print("Flattenning the 2-D array to 1-D array is:",newarr)

Changing shape of array from 1-D to 2-D: 
 [[1 2]
 [3 4]
 [5 6]]


Changing shape of 1-D array to 3-D array: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Changing the array shape: 
 [[1 2 3]
 [4 5 6]]
The Returned array is: [1 2 3 4 5 6] so it is View


Array changing shape froom 1-D to 3-D: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattenning the 2-D array to 1-D array is: [1 2 3 4 5 6]


# **1.5 Iterating in Numpy Array**

In [ ]:
#Iterating means to traversing each element .
#[For 1-D Array ]
import numpy as np
arr = np.array([1,2,3])
for x in arr:
  print(x)
print('\n')

#[For 2-D Array]
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x) #[Here we got two row not each element as indivisual]
print('\n')

#[[To Iterate on each scalar element of the 2-D array]]
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print("To print each element in the array:",y)
print('\n')

#[For 3-D Array]
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  print(x)
print('\n')

#[[T0 print  3-D Row by Row]]
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    print(y)
print('\n')

#[[To print each and every single element]]
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print("Each element of array is:")
      print(z)
print('\n')
    

1
2
3


[1 2 3]
[4 5 6]


To print each element in the array: 1
To print each element in the array: 2
To print each element in the array: 3
To print each element in the array: 4
To print each element in the array: 5
To print each element in the array: 6


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


Each element of array is:
1
Each element of array is:
2
Each element of array is:
3
Each element of array is:
4
Each element of array is:
5
Each element of array is:
6
Each element of array is:
7
Each element of array is:
8
Each element of array is:
9
Each element of array is:
10
Each element of array is:
11
Each element of array is:
12




In [ ]:
#Iterarting array using nditer(){As by using it we haven't use more for loops}
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
  print(x)
print('\n')

#Let's try it in 3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#Iterating Array with Different Data Types
import numpy as np
arr = np.array([1,2,3,4])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'


In [ ]:
#Iterating Array with Different Step size
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, : :2]):
  print(x)

1
3
5
7


In [ ]:
#Enumerated Iteration using ndenumerated()[Enumeration means mentioning sequence number of somethings one by one.]
#For 1-D Array
import numpy as np
arr = np.array([1,2,3,4])
for idr, x in np.ndenumerate(arr):
  print(idr ,x)
print('\n') 

#For 2-D Array
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i, x  in np.ndenumerate(arr):
  print(i, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## **1.6 Joining Array in Numpy**

In [ ]:
#Joinning array using Concatenate() fun.
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)
print('\n')

#Joinning Two arrays using (axis=1)
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[1 2 3 4 5 6 7 8]


[[1 2 5 6]
 [3 4 7 8]]


### **1.6.1 Joinning arrays using Stack function.**

In [ ]:
#Stack is as similar as concatenate but the difference is that stacking is done along a new axis.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Stacking along Rows(Using hstack() function)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)
print('\n')

#Stacking along Colums(Using vstack() function)

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

#Stacking along Height(Using dstack() function)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

print('\n')


[1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


